spring.application.name=optialloc

spring.datasource.url=jdbc:postgresql://localhost:5432/optialloc
spring.datasource.username=postgres
spring.datasource.password=YOUR_PASSWORD
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

spring.data.redis.host=localhost
spring.data.redis.port=6379

jwt.secret=YOUR_ACTUAL_SECRET