spring.application.name=optialloc

spring.datasource.url=${OPTIALLOC_DB_URL:jdbc:postgresql://localhost:5432/optialloc}
spring.datasource.username=${OPTIALLOC_DB_USERNAME:postgres}
spring.datasource.password=${OPTIALLOC_DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
#redis

spring.data.redis.host=localhost
spring.data.redis.port=6379

jwt.secret=${OPTIALLOC_JWT_SECRET:OptiAllocSuperSecretJwtKeyForAuthentication2026}